### ISSUE TITLE
title refactoring

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#12]
**🚀 What is the feature?**

Refactor the title of the page:

`<title>Quiz App clone</title>`

Remove the word "clone" from the title.

Add an icon to the title. Try to google how to do that, if not familiar.

**ℹ️ Additional info**

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by Vasilistaxo** [comment]
I would like to work with this one please. Thank you.

**Comment by benbenben147147147** [comment]
Done
