### ISSUE TITLE
read the question.json

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#14]
**🚀 What is the feature?**

We have stored all available questions for the quiz in the [questions.json](https://github.com/benbenben147147147/Quiz-to-Contribute-OSS/blob/main/questions.json) file.

As a next step read this array of json objects when loading the page and print them on the console.

**ℹ️ Additional info**

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by Vasilistaxo** [comment]
I would like to proceed with this one please.
