### ISSUE TITLE
create more questions

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#15]
**🚀 What is the feature?**

Create more questions, such that we can further improve the capabilities of our app.

For now, create 3 more questions.

Note: if you are not sure where to add the questions, scroll through the available files in the repository.

**ℹ️ Additional info**

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by nithindante** [comment]
Can I try working on this one ?

**Comment by benbenben147147147** [comment]
Yes please! There you go 🕺

**Comment by nithindante** [comment]
Hey, just a small doubt, you have mentioned to add a screenshot, Should I add a screenshot of the Webpage or my code ?

**Comment by benbenben147147147** [comment]
Normally as you see fit, but for this one, it's not necessary.

**Comment by mdiab1** [comment]
@nithindante where did you get the questions?

**Comment by nithindante** [comment]
@mdiab1  I just got some random info from google
