### ISSUE TITLE
add more questions

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#20]
🚀 What is the feature?

Create more questions, such that we can further improve the capabilities of our app.

For now, create 3 more questions.

Note: if you are not sure where to add the questions, scroll through the available files in the repository.

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by Vasilistaxo** [comment]
I would like to add more questions to the json file.

**Comment by Vasilistaxo** [comment]
If this is still valid , I could add some more questions to populate our json file.
