### ISSUE TITLE
Fix headings

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#22]
🚀 What is the feature?

For now, we have a short sentence "After finishing this quiz we are going to have knowledge of certain geographcal aspects and have fun" about our project **before** the "Geography World Class Quiz" title heading.

Put the sentence after the title heading and make it to a `<p>` tag, not a `<h1>` tag.

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by Vasilistaxo** [comment]
Assign me with this one please.

**Comment by benbenben147147147** [comment]
The idea is to complete each issue in a separate PR. This maintains traceability of issues and commits. Just keep that in mind :)

I can assign you once you are done with the already assigned issues to you. Assuming that soon more people will join to code here.

**Comment by Vasilistaxo** [comment]
Ok sure. That seems right. I have completed all the tasks though, I thought I would send some feedback with the appropriate comments above code and explanation of what I did in one shot. Should I split the changes into parts and send back the task answers individually?

**Comment by Vasilistaxo** [comment]
Ok for sure. Thank you!
