### ISSUE TITLE
center the content

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#23]
🚀 What is the feature?

Write CSS code such that all the html elements (question_id, category, question, answer_possibilities) are centered on the page.

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by nithindante** [comment]
Hey, can I work on this ?

**Comment by benbenben147147147** [comment]
Sure thing, i'll assign you.

Make sure to link your PR to that issue ;)
