### ISSUE TITLE
new page "settings.html

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#26]
🚀 What is the feature?

We want to provide the possibility for people to customize the 'look and feel' of the webapp.

The first step to accomplish that is to create a new html page 'settings.html'.

Therefore, the task is to create this new html file with the basic html file structure.

To be able to navigate back from this settings page, introduce also a link that leads back to the index.html page.

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by nithindante** [comment]
Can I work on this ?
