### ISSUE TITLE
Hover effect (css)

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#31]
🚀 What is the feature?

When hovering with the mouse over the answer possibilities, it would be nice to get some feedback.

Therefore, add css styling such that when hovering over the answer possibilities, the text gets highlighted.

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by Vasilistaxo** [comment]
I could add some hovering effect to that. Thank you in advance.

**Comment by benbenben147147147** [comment]
Assigned you ;)
