### ISSUE TITLE
heading for settings.html

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#37]
🚀 What is the feature?

Create a h1 heading for the settings.html file.

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by Theewebwizard** [comment]
i'll be happy to do that

**Comment by benbenben147147147** [comment]
Sure thing!
