### ISSUE TITLE
Settings link

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#38]
🚀 What is the feature?

We need a link in the index.html file to navigate to the settings.html file.

The respective link in the settings.html is already there, so we should then be able to navigate back and forth between those two pages.

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by mdiab1** [comment]
@benbenben147147147 I can take a look at this if you want to assign it to me.
