### ISSUE TITLE
Create heading

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#4]
**🚀 What is the feature?**

Create a html heading for the app, such that people know, that this app is all about. Feel free to be creative. 🕺

**ℹ️ Additional info**

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by Vasilistaxo** [comment]
I would like to have this done. If I can be assigned,please!

**Comment by benbenben147147147** [comment]
Sure, I'll assign you :)
