### ISSUE TITLE
Quiz overview

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#41]
🚀 What is the feature?

Create a new html file "quiz-overview.html" and create the basic html file structure.

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by mdiab1** [comment]
I'll do it.

**Comment by benbenben147147147** [comment]
sure thing, ill assign you!
