### ISSUE TITLE
Statistics overview

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#42]
🚀 What is the feature?

Create a new "statistics.js" file that can store the players statistics such as "totalQuestions" or "correctanswers".

You are welcome to get creative on that one, and make suggestions about what we could compute here. 🕺

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by subhashree9898** [comment]
please assign this issue to me.

**Comment by benbenben147147147** [comment]
Yes sure!
