### ISSUE TITLE
Basic html elements for displaying questions

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#5]
**🚀 What is the feature?**

For our quiz app we need some basic html elements in which we can display a question.
Therefore, we need html elements for the following components:
- question_id
- category
- question
- answer possibilities (array)
- correct answer index

The respective issue for the data structure of the questions is already written, but not implemented yet. Therefore, just focus on adding the html elements as a blueprint into the [index.html](https://github.com/benbenben147147147/Quiz-to-Contribute-OSS/blob/main/index.html) file, without actual content in them. Maybe just fill with some placeholder values, such that we see something.

Note: Don't worry about styling for now. Another issue for that will be written.

**ℹ️ Additional info**

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by Vasilistaxo** [comment]
I would like to update the html file with the respective fields for the questions.
If i could have this assigned please.

**Comment by benbenben147147147** [comment]
Yes, please! Happy coding 🕺
