### ISSUE TITLE
Make the number of total questions a variable

### ISSUE THREAD

**Issue by mdiab1** [benbenben147147147/Quiz-to-Contribute-OSS#50]
🚀 What is the feature?

Make the number of questions a configuration. It should be the min between the total number of available questions and a constant that we define in the code. 

You are welcome to get creative on that one, and make suggestions about what we could compute here. 🕺

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by subhashree9898** [comment]
@mdiab1 Please assign this issue to me.

**Comment by mdiab1** [comment]
Done, thanks!

**Comment by subhashree9898** [comment]
@mdiab1 Please see the pull request
https://github.com/benbenben147147147/Quiz-to-Contribute-OSS/pull/56

**Comment by mdiab1** [comment]
@subhashree9898 thanks for getting this done!
