### ISSUE TITLE
In settings page, add drop down for number of questions

### ISSUE THREAD

**Issue by mdiab1** [benbenben147147147/Quiz-to-Contribute-OSS#51]
🚀 What is the feature?

Add a drop-down called "Number of Questions" that allows the user to set the total number of questions. 
Link this to the change in issue #50 such that the variable is updated based on user selection. 

You are welcome to get creative on that one, and make suggestions about what we could compute here. 🕺

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by nithindante** [comment]
Hey, can I work on this ?

**Comment by mdiab1** [comment]
Sure, thanks!

**Comment by mdiab1** [comment]
@nithindante I'm thinking from a user's perspective, how many options would make sense, and which options should we choose? For example, it doesn't make sense to have an option for 1 question. What do you think?

**Comment by nithindante** [comment]
Thanks for getting back,   ooh I didnt think like that,  yes, an option for 1 question shouldn't have been there, it should have been default 


also would it be good if, we give options for either 1,5 or 10 , Am I thinking it rightly ?

**Comment by mdiab1** [comment]
I would recommend 5, 10, 20. I don't think users are going to want to take a quiz with one question :)

**Comment by nithindante** [comment]
oooh right
