### ISSUE TITLE
Add 10 more questions

### ISSUE THREAD

**Issue by mdiab1** [benbenben147147147/Quiz-to-Contribute-OSS#52]
🚀 What is the feature?

Write a script to do this create a new file called "new_questions.json". Use the API here https://opentdb.com/api_config.php to get the question data. Make 5 calls (50 results each) with 5 different categories then combine the results into one file. Let me know if you have any questions. 

You are welcome to get creative on that one, and make suggestions about what we could compute here. 🕺

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by RichardAri** [comment]
can you assign me this issue?

**Comment by mdiab1** [comment]
@RichardAri do you think you can write a script to call the api 10 times for 10 categories and create a new json file called "new-questions.json" with an array of JSON objects for the aggregated data?

**Comment by benbenben147147147** [comment]
yep, thanks you!

**Comment by mdiab1** [comment]
https://opentdb.com/api_config.php

**Comment by mdiab1** [comment]
@RichardAri obviously that's more complicated that the original ticket, but that's the better approach. Let me know if you still would like to tackle it and I'll update the description

**Comment by RichardAri** [comment]
> @RichardAri obviously that's more complicated that the original ticket, but that's the better approach. Let me know if you still would like to tackle it and I'll update the description

Sure no problem

**Comment by mdiab1** [comment]
@RichardAri don't worry about the category in index.html for now. We just need to create a new file then we can update index.js to use it. I'm happy to hop on a voice chat on discord if you want to discuss this.

**Comment by RichardAri** [comment]
> @RichardAri don't worry about the category in index.html for now. We just need to create a new file then we can update index.js to use it. I'm happy to hop on a voice chat on discord if you want to discuss this.

Sure addme : richardcap

**Comment by mdiab1** [comment]
https://discord.gg/nBbqNz4R
