### ISSUE TITLE
separate frontend from backend

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#53]
🚀 What is the feature?

We plan to create an api for our webapp. The idea is that the api provides endpoints for retrieving and storing highscores of other players. To achieve that, the first step is to organize (separate) our code accordinly.

Create a package "frontend" and put everything in that package that belongs to that frontend application (pretty much everything we have). Then also create a package "backend". For now, no need to put any files in that package.

Note: Packages are just folders.

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by Theewebwizard** [comment]
will do it

**Comment by benbenben147147147** [comment]
🌟
