### ISSUE TITLE
background settings.html

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#63]
🚀 What is the feature?

The background in the settings.html file looks a bit dull. Please change the color to a better color...be creative here 🕺

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by 27Lia** [comment]
Can I work on this ?

**Comment by benbenben147147147** [comment]
Definitely! Have fun :)

**Comment by 27Lia** [comment]
When I checked locally, I noticed that the index.html page is not properly aligned, and I would like to fix this as well. Additionally, do you have a specific background style in mind? Are you looking for something interactive, or do you prefer a simpler design? @benbenben147147147

**Comment by benbenben147147147** [comment]
Yeah sure, you can be creative and adjust the design to your liking :)
