### ISSUE TITLE
background quiz-overview.html

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#64]
🚀 What is the feature?

The background in the quiz-overview.html file looks a bit dull. Please change the color to a better color...be creative here 🕺

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by nithindante** [comment]
Can I work on this ?

**Comment by subhashree9898** [comment]
Can you assign it to me?

**Comment by benbenben147147147** [comment]
sure

**Comment by subhashree9898** [comment]
@benbenben147147147 please see the PR https://github.com/benbenben147147147/Quiz-to-Contribute-OSS/pull/88
