### ISSUE TITLE
Heading index.html

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#65]
🚀 What is the feature?

In the index.html file, the content of the h1 heading is not really fitting anymore. Please choose a new heading...be creative here 🕺

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by nithindante** [comment]
Can I work on this ?

**Comment by benbenben147147147** [comment]
yure, ill assign you 🕺
