### ISSUE TITLE
create new folder and calculator.js file

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#66]
🚀 What is the feature?

In the future we will need some methods that are used from a lot of places. Therefore, create in the frontend package a new "utils" directory. In this directory create a new file "calculator.js".

As a start, define in this file a method "add()", that accepts 2 parameters, adds them, and returns them.

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by jxSankalp** [comment]
Please assign this to me

**Comment by benbenben147147147** [comment]
Have fun :)
