### ISSUE TITLE
Use Google fonts

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#67]
🚀 What is the feature?

We need fetter fonts...definitely. In this issue, please have a look at how we can use google fonts in our application. As a start, change the default font in the settings.html to a google font of your choice.

... as always, be creative here 🕺

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by nithindante** [comment]
Can I work on this, if you all dont mind?

**Comment by benbenben147147147** [comment]
Sure, thanks for taking this on ;)

**Comment by nithindante** [comment]
A lil confused, Can I link the style.css to our settings.html and then update the font via CSS or use inline style to update it then and there ? First approach would be better I think

**Comment by benbenben147147147** [comment]
I would import the google fonts in the settings.html via a "link" tag. Then you can use the font family in the styles.css file. Note: To see the changes, you would each time need to rebuild the output.css file by executing the command "npm run build". Does this help?

**Comment by nithindante** [comment]
ooh okay,  Sure, I can do that,  lil confused,  the font family I am importing should  it be used in every page or just in settings.html?

**Comment by benbenben147147147** [comment]
i think in every page would make sense.

**Comment by nithindante** [comment]
ooh okay, thanks, I think I did the pull request wrong as well
