### ISSUE TITLE
Create a navigation bar

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#68]
🚀 What is the feature?

We have 3 .html files so far (index.html, settings.html, quiz-overview.html). You can already navigate from one to the other, but not in a nice way. Please implement a navigation bar, that is at the top of the screen and provides the possibility to navigate to either one of those pages. For now, only implement this navigation bar in the index.html file.🕺

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by nithindante** [comment]
Can I work on this ?

**Comment by benbenben147147147** [comment]
Yep of course!

**Comment by nithindante** [comment]
I have created a PR,  but I think I did it the wrong way
