### ISSUE TITLE
Css background

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#7]
**🚀 What is the feature?**

So far, we have no css styling at all.

The task here, is to set a basic background. Now, it is just the default white. You can be creative :)

**ℹ️ Additional info**

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by Vasilistaxo** [comment]
I would like to do the changes please.

**Comment by benbenben147147147** [comment]
There you go :)

Note: Make sure to link your PR to the respective issue. The reason for that is, that when I approve the PR, this issue will be closed automatically 🌟
