### ISSUE TITLE
tracking score

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#77]
🚀 What is the feature?

For now, we are displaying quiz questions correctly on the screen. But we are not tracking the total score of the session yet.

Provide a way to display the current score to the user. You can think about something cool yourself, but I would suggest that we need something like "[3/5]" (e.g. 3 correct out of 5) as a minimum requirement.

Have fun!

<img width="684" alt="quiz" src="https://github.com/benbenben147147147/Quiz-to-Contribute-OSS/assets/171587125/eb6d54b6-1bb2-4a15-8b73-b37a3ec1c6f1">

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

**Comment by subhashree9898** [comment]
@benbenben147147147 please assign this issue to me

**Comment by benbenben147147147** [comment]
Sure!

**Comment by subhashree9898** [comment]
@benbenben147147147 please see the pr https://github.com/benbenben147147147/Quiz-to-Contribute-OSS/pull/90
