### ISSUE TITLE
quiz: improve hover styling

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#78]
🚀 What is the feature?

Our quiz looks pretty nice so far. But we would like to make the UI more responsive to user actions. As a first step, add a hover effect, when the user is hovering over the "Quiz Overview" and "Settings" buttons.

You can definitely get creative with that one 💯 

<img width="720" alt="Screenshot 2024-06-09 at 18 23 11" src="https://github.com/benbenben147147147/Quiz-to-Contribute-OSS/assets/171587125/5393b4d2-567f-44a6-9a63-1e9c13d6095d">

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

**Comment by LakshyaKhilwani** [comment]
Interested to work upon this issue.

**Comment by benbenben147147147** [comment]
Yes, I assign you!
