### ISSUE TITLE
new method that selects a random question from an array of questions

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#8]
**🚀 What is the feature?**

Write a function that accepts an array of question objects.

The function should randomly select one of those questions and return the chosen question object.

**ℹ️ Additional info**

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by Vasilistaxo** [comment]
I would like to get to the ends of this one please.

**Comment by benbenben147147147** [comment]
Done
