### ISSUE TITLE
settings: css (centering elements)

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#81]
🚀 What is the feature?

Please center the html element for selecting the number of questions.

<img width="1440" alt="Settings" src="https://github.com/benbenben147147147/Quiz-to-Contribute-OSS/assets/171587125/390b1c04-ac21-4c9b-a51b-625539f54c50">

ℹ️ Additional info

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

**Comment by LakshyaKhilwani** [comment]
Hello
I would like to solve this issue.

**Comment by benbenben147147147** [comment]
🕺 Sure!
Let's go :)
