### ISSUE TITLE
introductory text

### ISSUE THREAD

**Issue by benbenben147147147** [benbenben147147147/Quiz-to-Contribute-OSS#9]
**🚀 What is the feature?**

Write a short introductory text, that explains some basics about the webapp quiz - what is it, what it does, ...

This text should appear within a <p> tag in the [index.html](https://github.com/benbenben147147147/Quiz-to-Contribute-OSS/blob/main/index.html) file.

Also, you're welcome to get creative.

**ℹ️ Additional info**

Add a screenshot of your changes - if helpful.

Make sure the app works, otherwise the PR cannot be approved.

Link the PR with this issue (in the right panel "Development" -> select issue).

**Comment by Vasilistaxo** [comment]
Assign me please with this one. Thank you!

**Comment by benbenben147147147** [comment]
Done ;)
